name: CI/CD Pipeline  Supabase

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main  # Ya tumhari branch jahan tum code push karte ho

jobs:
  build:
    runs-on: ubuntu-latest  # Ubuntu environment for the build

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Tumhare project ke liye jo Node.js version ho, wo set karo

      # Step 3: Install dependencies (for Next.js, React, Tailwind CSS, and TypeScript)
      - name: Install dependencies
        run: |
          npm install  # npm use kar rahe hain, agar yarn use karte ho toh yarn install karo

      # Step 4: Build the project (Next.js build)
      - name: Build Next.js project
        run: npm run build  # Ye command Next.js app ko build karega

  deploy:
    runs-on: ubuntu-latest  # Ubuntu environment for deployment
    needs: build  # Ensure build job runs before deploying
    steps:
      # Step 1: Checkout code again in the deploy job
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install Supabase CLI (if using Supabase CLI for deployment)
      - name: Install Supabase CLI
        run: |
          curl -sL https://github.com/supabase/cli/releases/download/v1.0.0/supabase_1.0.0_linux_amd64.tar.gz | tar xz
          sudo mv supabase /usr/local/bin

      # Step 3: Configure Supabase CLI with environment variables (add them in GitHub secrets)
      - name: Configure Supabase Environment Variables
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> $GITHUB_ENV
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> $GITHUB_ENV

      # Step 4: Deploy to Supabase (if using Supabase for deployment)
      - name: Deploy to Supabase
        run: |
          # Example Supabase command for deploying your project
          supabase db push  # Database changes ko push karne ke liye
          supabase deploy  # Agar tum frontend deploy kar rahe ho
